"""empty message

Revision ID: d7cf7bedb7d7
Revises: ef8437f9ca63
Create Date: 2023-03-02 00:51:49.268049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7cf7bedb7d7'
down_revision = 'ef8437f9ca63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['character_id'])
        batch_op.create_unique_constraint(None, ['planet_id'])
        batch_op.create_unique_constraint(None, ['vehicle_id'])
        batch_op.create_unique_constraint(None, ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
